### ISSUE TITLE
Build failed after update

### ISSUE THREAD

**Issue by alexsmartens** [react-community/lottie-react-native#312] opened 2018-04-03 22:48 UTC
After update to 2.5.0 version (from 2.3.2) build is failing. 

I followed the suggestions in #204, but it did not help

> unlink lottie-ios
unlink lottie-react-native
clean the build
clean the build folder
close XCode
remove node modules
reinstall node modules
relink the 2 lotties

Here is my error:
```
:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.io.IOException: Unable to create parent directories of C:\MY-PATH\MY-App\android\app\build\intermediates\pre-dexed\debug\debug_880a1d403a26662e8fd01c1b2464619f21568126.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Any ideas?

**Comment by anandprabhu** [comment] 2018-04-04 07:50
Hi @alexsmartens can you try to remove the below 2 build folders and try building the app again
`android/build`
`android/app/build`

**Comment by emilioicai** [comment] 2018-04-04 09:59
@alexsmartens check your `android/settings.gradle` to make sure you don't have duplicated entries for `lottie-react-native`, you should only have these two lines(for lottie):

```
include ':lottie-react-native'
project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')
```

**Comment by alexsmartens** [comment] 2018-04-04 16:36
@anandprabhu: I tried deleting `android/build` & `android/app/build` & `node_modules` and compiling the app again. This did not help 

@emilioicai: I checked `android/settings.gradle`, there are no duplicates. I also double checked that all the installation changes mentioned in [Lottie guide](http://airbnb.io/lottie/react-native/react-native.html) are in place

**Comment by anandprabhu** [comment] 2018-04-04 18:57
@alexsmartens Can you try adding this to your `android/app/build.gradle` and check if it works
```gradle
defaultConfig {
    multiDexEnabled true
}
```

**Comment by alexsmartens** [comment] 2018-04-16 20:40
The problem is not solved. I'm using the 2.3.2 version for now

**Comment by clementinoux** [comment] 2018-07-01 13:16
Any news ?

**Comment by sdkumar25** [comment] 2018-07-03 10:49
Any update on this issue?

**Comment by emilioicai** [comment] 2018-07-03 11:02
It looks like an issue with gradle cache. Try going to the folder the process is failing to create and delete its cache folder.

If that fails, try running Android Studio as an admin so it has enough privileges to crate the folder.

**Comment by ali-torabi-intive** [comment] 2018-07-03 14:46
My project is breaking all of a sudden.
It was working fine until yesterday, now it breaks with same issue.

**Comment by ali-torabi-intive** [comment] 2018-07-03 14:54
In `app/build.gradle`

add this 👍 

```
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
```

Works fine

**Comment by sdkumar25** [comment] 2018-07-04 07:02
I have tried above solution but that didn't work for me. So for now i stick with version 2.3.+ till the issue get resolved.

**Comment by MohanadeviK** [comment] 2018-07-07 17:45
@sdkumar25 Any update?

**Comment by sdkumar25** [comment] 2018-07-09 12:38
@MohanadeviK We have tried to build the app with version 2.5.+ and issue still exists So, I downgraded the version from 2.5.+ to 2.3.+ for now to proceed the development.

**Comment by flavordaaave** [comment] 2018-07-17 16:57
I'm having the same issues.
I tried with multidex but still got some build errors so for now I downgraded back to 2.3.2...

**Comment by AibiTi** [comment] 2018-07-19 03:56
```js
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.lang.UnsupportedOperationException (no error message)
```

**Comment by emilioicai** [comment] 2018-08-01 15:33
I managed to reproduce, 2.5.0 was indeed buggy. This should be fixed in 2.5.6, @alexsmartens can you give it a try and let me know? thanks!

**Closed by emilioicai** 2018-08-01 15:33 UTC

**Comment by digrase008** [comment] 2018-08-07 04:44
Hey try this once folder generated go to particular path and assign full access to that folder and remove read only check that one is working for me

**Comment by assemmohamedali** [comment] 2018-08-24 22:29
This problem should be solved using these two lines only at least for me :smile: 
`android/app/build.gradle`

~~~
implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
implementation "com.android.support:design:${rootProject.ext.supportLibVersion}"
~~~

* Insread of ${rootProject.ext.supportLibVersion} put 27.1.0 as the library I think require that version

**Comment by RafaelAugustoS** [comment] 2019-01-11 19:22
> In `app/build.gradle`
> 
> add this 👍
> 
> ```
>     compileOptions {
>         sourceCompatibility 1.8
>         targetCompatibility 1.8
>     }
> ```
> Works fine

It's work for me

**Comment by ericdolson** [comment] 2019-01-13 05:39
8 hours of hitting my head against the wall today and FINALLY came across this. Thank you @ali-torabi-intive, your fix worked for me.

**Comment by kardoqadir** [comment] 2019-01-25 08:58
> In `app/build.gradle`
> 
> add this 👍
> 
> ```
>     compileOptions {
>         sourceCompatibility 1.8
>         targetCompatibility 1.8
>     }
> ```
> 
> Works fine

It should be inside android {...}, Thanks man 👏🏻👏🏻👏🏻

**Comment by letrinhthanhvn** [comment] 2019-05-23 03:08
> > In `app/build.gradle`
> > add this 👍
> > ```
> >     compileOptions {
> >         sourceCompatibility 1.8
> >         targetCompatibility 1.8
> >     }
> > ```
> > 
> > 
> > Works fine
> 
> It should be inside android {...}, Thanks man 👏🏻👏🏻👏🏻

save my day. it worked for me! Thanks a lot!

**Comment by prasad-dumbre-10** [comment] 2019-06-15 09:29
>  compileOptions {
>         sourceCompatibility 1.8
>         targetCompatibility 1.8
>     }

thanks man very much
